### ISSUE TITLE
calcule du déterminant

### ISSUE THREAD

**Issue by JeanEdouardPld** [mdiazmel/winelabelproject#2]
nous avons revu les étapes du calcul mais malheureusement nous n'avons pas réussi a détermener les causes des erreurs du au calcul des déterminants

**Comment by mdiazmel** [comment]
Bonjour à tous,
Il me semble qu'on avait oublié les pas 3 de l'algorithme, la normalisation des vectors v1 et v2. J'ai ajouté ça au script. Désormais, le determinant de R est +/- 1, il faut choisir les bonnes matrices R. 
J'ai ajouté aussi d'autres commentaires au code.
